### ISSUE TITLE
视频播放页评论加载动画慢，可以快一点或者关闭动画吗？

### ISSUE THREAD

**Issue by deckvig** [gogofishman/BlibliBeautify#1]
视频播放页评论加载动画慢，可以调整快一点或者提供开关关闭动画吗？

**Comment by gogofishman** [comment]
我明天弄一下

**Comment by gogofishman** [comment]
研究了一下，我把动画时间从1.5s改到0.5s了，想再快或者取消这个的话，页面会很乱，因为这个网页很傻逼，第一次加载一丢丢，过几秒又会重载一遍把剩下的加载完。现在感官会比之前提高不少，开关我就不加了，因为主打一个简洁无操作
